version: '3.8'

services:
  twitter_copy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PORT: ${DB_PORT}
      KEYCLOAK_SERVER_BASE_URL: ${KEYCLOAK_SERVER_BASE_URL}
      KEYCLOAK_SERVER_PUBLIC_BASE_URL: ${KEYCLOAK_SERVER_PUBLIC_BASE_URL}
      KEYCLOAK_SERVER_PRIVATE_BASE_URL: ${KEYCLOAK_SERVER_PRIVATE_BASE_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    volumes:
      - ./app/:/app
    ports:
      - 8000:80
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}:5432

#  keycloak:
#    image: quay.io/keycloak/keycloak:latest
#    environment:
#      DB_VENDOR: ${KEYCLOAK_DB_VENDOR}
#      DB_ADDR: ${KEYCLOAK_DB_ADDR}
#      DB_DATABASE: ${KEYCLOAK_DB_DATABASE}
#      DB_USER: ${DB_USER}
#      DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
#      DB_PASSWORD: ${DB_PASSWORD}
#      KEYCLOAK_USER: ${KEYCLOAK_KEYCLOAK_USER}
#      KEYCLOAK_PASSWORD: ${KEYCLOAK_KEYCLOAK_PASSWORD}
#    ports:
#      - 8080:8080
#    depends_on:
#      - database